theme: jekyll-theme-architect
title: My Site
author: me
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  A GitHub site.
# social links
twitter_username: mdzi_ny
github_username:  mdzi

show_excerpts: false # set to false to remove excerpts on the homepage
